# Generated by Django 4.2.9 on 2024-01-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job_date_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
