# Generated by Django 4.2.9 on 2024-01-11 23:17

from django.db import migrations
from django.utils.text import slugify

def generate_job_slugs(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Job = apps.get_model("app", "Job")
    for job in Job.objects.all():
        job.slug = slugify(job.title + "-" + job.company)
        job.save()

def do_nothing(*args):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_slug'),
    ]

    operations = [
        migrations.RunPython(generate_job_slugs, do_nothing),
    ]
